/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package repeated.word.lambda;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void test_string() {
        Library classUnderTest = new Library();
        assertEquals("Should return a string of 'the' ", "the", classUnderTest.repeatedWord("A cat a hat"));
    }
}
