/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package repeated.word.lambda;

import java.util.HashSet;

public class Library {
    public static String repeatedWord(String input){
        if(input == null) return null;
        HashSet<String> hashset = new HashSet<>();
        String[] wordList = input.split(" ");
        for(int i = 0; i < wordList.length; i++){
            if(hashset.contains(wordList[i].toLowerCase())) return wordList[i];
            else hashset.add(wordList[i].toLowerCase());
        }
        return null;
    }
}
